export const fees = [
  { name: "TUITION AND MISCELLANEOUS FEES", categories: ["REG", "GS"] },
  { name: "ALUMNI FEE", categories: ["REG"] },
  { name: "BIDDER'S BOND - DISPOSAL", categories: ["REG"] },
  { name: "BID SECURITY - PROCUREMENT", categories: ["REG"] },
  { name: "CERTIFICATION - CAV", categories: ["REG"] },
  { name: "CERTIFICATION - Enrollment Form", categories: ["REG"] },
  { name: "CERTIFICATION - Good Moral Character", categories: ["REG"] },
  { name: "CERTIFICATION - Grades/Rating", categories: ["REG"] },
  { name: "CERTIFICATION - Guidance", categories: ["REG"] },
  { name: "CERTIFICATION - HR", categories: ["REG"] },
  { name: "CERTIFICATION - Registrar", categories: ["REG"] },
  { name: "CERTIFICATION - Statement of Account", categories: ["REG"] },
  { name: "CERTIFICATION - OSAS", categories: ["REG"] },
  { name: "CERTIFICATION - Other", categories: ["REG"] },
  { name: "CERTIFIED PHOTOCOPY", categories: ["REG"] },
  { name: "DIPLOMA", categories: ["REG"] },
  { name: "DIPLOMA RECONSTRUCTION", categories: ["REG"] },
  { name: "DOCUMENTARY STAMP TAX", categories: ["REG"] },
  { name: "ENTRANCE EXAM/GUIDANCE TESTING FEE", categories: ["REG"] },
  { name: "FINANCIAL ASSISTANCE", categories: ["REG"] },
  { name: "FINES/PENALTY", categories: ["REG"] },
  { name: "GRADUATION FEE", categories: ["REG"] },
  { name: "ID CARD - NEW/DAMAGED/LOST", categories: ["REG"] },
  { name: "ID STICKER", categories: ["REG"] },
  { name: "LIBRARY FINES", categories: ["REG"] },
  { name: "LIBRARY FEES", categories: ["REG"] },
  { name: "PERFORMANCE SECURITY", categories: ["REG"] },
  { name: "REFUND", categories: ["REG"] },
  { name: "REGISTRAR FEES", categories: ["REG"] },
  { name: "REGISTRATION FEE", categories: ["REG"] },
  { name: "SALE OF BID DOCUMENTS - DISPOSAL", categories: ["REG"] },
  { name: "SALE OF BID DOCUMENTS - PROCUREMENT", categories: ["REG"] },
  { name: "SCHOLARSHIP GRANT", categories: ["REG"] },
  { name: "TRANSCRIPT OF RECORDS", categories: ["REG"] },
  { name: "TRANSFER CREDENTIALS", categories: ["REG"] },
  { name: "VERIFICATION/AUTHENTICATION FEE", categories: ["REG"] },
  { name: "OTHERS", categories: ["REG"] },
  { name: "CANTEEN - CAFETERIA", categories: ["IGP"] },
  { name: "CANTEEN - CATERING SERVICES", categories: ["IGP"] },
  { name: "CANTEEN - SNACKBAR", categories: ["IGP"] },
  { name: "CAR/VEHICLE PASS", categories: ["IGP"] },
  { name: "COPYRIGHT PROCESSING FEE", categories: ["IGP"] },
  { name: "ELECTRICITY BILL", categories: ["IGP"] },
  { name: "FAB LAB SERVICES", categories: ["IGP"] },
  { name: "FINES/PENALTY - BAO", categories: ["IGP"] },
  { name: "FITNESS CENTER", categories: ["IGP"] },
  { name: "ID CORD -  FACULTY & STAFF", categories: ["IGP"] },
  { name: "ID CORD -  STUDENT", categories: ["IGP"] },
  { name: "PHOTOCOPYING", categories: ["IGP"] },
  { name: "PRINTING PRESS SERVICES - Binding", categories: ["IGP"] },
  { name: "PRINTING PRESS SERVICES - Printing", categories: ["IGP"] },
  {
    name: "PRINTING PRESS SERVICES - Printing and Binding",
    categories: ["IGP"],
  },
  { name: "RENTAL - AVR", categories: ["IGP"] },
  { name: "RENTAL - BASKETBALL/COVERED COURT", categories: ["IGP"] },
  { name: "RENTAL - BILLETING VENUE", categories: ["IGP"] },
  { name: "RENTAL - BUS/VEHICLE", categories: ["IGP"] },
  { name: "RENTAL - CHAIRS", categories: ["IGP"] },
  { name: "RENTAL - CHAIR COVER", categories: ["IGP"] },
  { name: "RENTAL - DINING HALL", categories: ["IGP"] },
  { name: "RENTAL - DORMITORY", categories: ["IGP"] },
  { name: "RENTAL - FOOTBALL FIELD", categories: ["IGP"] },
  { name: "RENTAL - FUNCTION HALL", categories: ["IGP"] },
  { name: "RENTAL - GYM", categories: ["IGP"] },
  { name: "RENTAL - HOMETEL", categories: ["IGP"] },
  { name: "RENTAL - LOCKER", categories: ["IGP"] },
  { name: "RENTAL - SOUND SYSTEM", categories: ["IGP"] },
  { name: "RENTAL - SPACE", categories: ["IGP"] },
  { name: "RENTAL - STALL/KIOSK", categories: ["IGP"] },
  { name: "RENTAL - TABLE", categories: ["IGP"] },
  { name: "RENTAL - TOGA", categories: ["IGP"] },
  { name: "RENTAL - OTHER", categories: ["IGP"] },
  { name: "REIP SERVICES - GRAMMARLY/PLAGIARISM CHECK", categories: ["IGP"] },
  {
    name: "REIP SERVICES - IP APPLICATION CONSULTANCY FEE",
    categories: ["IGP"],
  },
  { name: "REIP SERVICES - PATENT PROCESSING FEE", categories: ["IGP"] },
  { name: "REIP SERVICES - UTILITY MODEL PROCESSING FEE", categories: ["IGP"] },
  { name: "RESEARCH/EXTENSION/IP SERVICES - OTHER", categories: ["IGP"] },
  { name: "SALE OF AGRICULTURAL/FARM PRODUCTS", categories: ["IGP"] },
  { name: "SALE OF FISH/FISH PRODUCTS", categories: ["IGP"] },
  { name: "SALE OF FIREWOOD", categories: ["IGP"] },
  { name: "SALE OF NSTP/ROTC UNIFORM", categories: ["IGP"] },
  { name: "SALE OF OJT UNIFORM", categories: ["IGP"] },
  { name: "SALE OF PE UNIFORM", categories: ["IGP"] },
  { name: "SALE OF PURIFIED DRINKING WATER", categories: ["IGP"] },
  { name: "SALE OF ROTC BALL CAP", categories: ["IGP"] },
  { name: "SALE OF UNSERVICEABLE PROPERTY", categories: ["IGP"] },
  { name: "SALE OF WASTE/SCRAP MATERIALS", categories: ["IGP"] },
  { name: "SALE - OTHER SALES", categories: ["IGP"] },
  { name: "SHOP SERVICES", categories: ["IGP"] },
  { name: "UNIVERSITY LOGO PATCH", categories: ["IGP"] },
  { name: "WATER BILL", categories: ["IGP"] },
  { name: "COMPREHENSIVE EXAM", categories: ["GS"] },
  { name: "GRADUATION FEE - GRADUATE SCHOOL", categories: ["GS"] },
];
